language: perl
install:
  - cpanm -n -q --skip-satisfied --installdeps .
before_script:
  - cpanm -n -q --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
script:
  - perl Build.PL && ./Build && ./Build test
  - cover -delete
  - perl -X -MDevel::Cover t/compile.t
  - perl -X -MDevel::Cover t/plugins.t
  - perl -X -MDevel::Cover t/engine.t
  - perl -X -MDevel::Cover t/importer.t
after_success:
  - cover -report codecov
perl:
  - "5.24"
  - "5.22"
  - "5.18"
  - "5.16"
  - "5.10"
